version: 2

sources:
  - name: northwind
    description: Data from Northwind ERP
    database: curso-etl-101
    schema: erp_northwind
    tables:
      - name: orders
        description: List of orders from ERP Northwind
        columns:
          - name: order_id
            description: Unique identification per order made
      - name: customers
        description: List of customers from ERP Northwind
        columns:
          - name: customer_id
            description: Unique identification per customer made
      - name: order_details
      - name: categories
      - name: products
      - name: suppliers
      